set_property INTERNAL_VREF 0.6 [get_iobanks 35]

set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVDS_25} [get_ports mipi_phy_if_0_clk_hs_p]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVDS_25} [get_ports mipi_phy_if_0_clk_hs_n]

set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVDS_25} [get_ports {mipi_phy_if_0_data_hs_p[0]}]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVDS_25} [get_ports {mipi_phy_if_0_data_hs_n[0]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVDS_25} [get_ports {mipi_phy_if_0_data_hs_p[1]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVDS_25} [get_ports {mipi_phy_if_0_data_hs_n[1]}]

set_property -dict {PACKAGE_PIN D20 IOSTANDARD HSUL_12} [get_ports mipi_phy_if_0_clk_lp_p]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD HSUL_12} [get_ports mipi_phy_if_0_clk_lp_n]

set_property -dict {PACKAGE_PIN E19 IOSTANDARD HSUL_12} [get_ports {mipi_phy_if_0_data_lp_p[0]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD HSUL_12} [get_ports {mipi_phy_if_0_data_lp_n[0]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD HSUL_12} [get_ports {mipi_phy_if_0_data_lp_p[1]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD HSUL_12} [get_ports {mipi_phy_if_0_data_lp_n[1]}]
set_property PACKAGE_PIN AA4 [get_ports {video_out[0]}]
set_property PACKAGE_PIN AB4 [get_ports {video_out[1]}]
set_property PACKAGE_PIN Y5 [get_ports {video_out[2]}]
set_property PACKAGE_PIN AB5 [get_ports {video_out[3]}]
set_property PACKAGE_PIN AA6 [get_ports {video_out[4]}]
set_property PACKAGE_PIN AA7 [get_ports {video_out[5]}]
set_property PACKAGE_PIN AB7 [get_ports {video_out[6]}]
set_property PACKAGE_PIN AA8 [get_ports {video_out[7]}]
set_property PACKAGE_PIN AA9 [get_ports {video_out[8]}]
set_property PACKAGE_PIN W8 [get_ports {video_out[9]}]
set_property PACKAGE_PIN Y8 [get_ports {video_out[10]}]
set_property PACKAGE_PIN V9 [get_ports {video_out[11]}]
set_property PACKAGE_PIN Y10 [get_ports {video_out[12]}]
set_property PACKAGE_PIN Y11 [get_ports {video_out[13]}]
set_property PACKAGE_PIN AA11 [get_ports {video_out[14]}]
set_property PACKAGE_PIN V8 [get_ports {video_out[15]}]
set_property PACKAGE_PIN V10 [get_ports {video_out[16]}]
set_property PACKAGE_PIN W10 [get_ports {video_out[17]}]
set_property PACKAGE_PIN W11 [get_ports {video_out[18]}]
set_property PACKAGE_PIN U10 [get_ports {video_out[19]}]
set_property PACKAGE_PIN AB12 [get_ports {video_out[23]}]
set_property PACKAGE_PIN AB11 [get_ports {video_out[22]}]
set_property PACKAGE_PIN AB10 [get_ports {video_out[21]}]
set_property PACKAGE_PIN U11 [get_ports {video_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_out[0]}]

set_property PACKAGE_PIN W12 [get_ports hdmi_IIC_scl_io]
set_property PACKAGE_PIN AA12 [get_ports hdmi_IIC_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_IIC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_IIC_sda_io]
set_property PACKAGE_PIN E18 [get_ports cam_IIC_scl_io]
set_property PACKAGE_PIN F19 [get_ports cam_IIC_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports cam_IIC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports cam_IIC_sda_io]

set_property PACKAGE_PIN Y4 [get_ports vid_out_active_video]
set_property PACKAGE_PIN Y6 [get_ports vid_out_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vid_out_active_video]
set_property IOSTANDARD LVCMOS33 [get_ports vid_out_hsync]

set_property SLEW FAST [get_ports {video_out[23]}]
set_property SLEW FAST [get_ports {video_out[22]}]
set_property SLEW FAST [get_ports {video_out[21]}]
set_property SLEW FAST [get_ports {video_out[20]}]
set_property SLEW FAST [get_ports {video_out[19]}]
set_property SLEW FAST [get_ports {video_out[18]}]
set_property SLEW FAST [get_ports {video_out[17]}]
set_property SLEW FAST [get_ports {video_out[16]}]
set_property SLEW FAST [get_ports {video_out[15]}]
set_property SLEW FAST [get_ports {video_out[14]}]
set_property SLEW FAST [get_ports {video_out[13]}]
set_property SLEW FAST [get_ports {video_out[12]}]
set_property SLEW FAST [get_ports {video_out[11]}]
set_property SLEW FAST [get_ports {video_out[10]}]
set_property SLEW FAST [get_ports {video_out[9]}]
set_property SLEW FAST [get_ports {video_out[8]}]
set_property SLEW FAST [get_ports {video_out[7]}]
set_property SLEW FAST [get_ports {video_out[6]}]
set_property SLEW FAST [get_ports {video_out[5]}]
set_property SLEW FAST [get_ports {video_out[4]}]
set_property SLEW FAST [get_ports {video_out[3]}]
set_property SLEW FAST [get_ports {video_out[2]}]
set_property SLEW FAST [get_ports {video_out[1]}]
set_property SLEW FAST [get_ports {video_out[0]}]
set_property SLEW FAST [get_ports vid_out_active_video]
set_property SLEW FAST [get_ports vid_out_hsync]
set_property PULLTYPE PULLUP [get_ports hdmi_IIC_scl_io]
set_property PULLTYPE PULLUP [get_ports hdmi_IIC_sda_io]
set_property PULLTYPE PULLUP [get_ports cam_IIC_scl_io]
set_property PULLTYPE PULLUP [get_ports cam_IIC_sda_io]

#set_property PACKAGE_PIN H19 [get_ports cam_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports cam_clk]

set_property PACKAGE_PIN A18 [get_ports {GPIO_0_tri_io[1]}]
set_property PACKAGE_PIN C18 [get_ports {GPIO_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[0]}]

set_property PACKAGE_PIN AB9 [get_ports video_out_clk]
set_property IOSTANDARD LVCMOS33 [get_ports video_out_clk]

set_property PACKAGE_PIN AB6 [get_ports vid_out_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vid_out_vsync]

set_property SLEW SLOW [get_ports {GPIO_0_tri_io[0]}]
set_property PULLTYPE PULLUP [get_ports {GPIO_0_tri_io[0]}]

set_property PULLTYPE PULLDOWN [get_ports {GPIO_0_tri_io[1]}]

set_property SLEW SLOW [get_ports {GPIO_0_tri_io[1]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets video_out_clk_OBUF]
